### ISSUE TITLE
Enhancement: ability to vendor multiple environment.yaml files into a single local-channel

### ISSUE THREAD

**Issue by rigzba21** [MetroStar/conda-vendor#25]
I ran into a situation where I needed to create two separate conda environments, each with different versions of the same package but solvable from a single conda-vendor'ed local channel. 

Example:
`environment-1.yaml`:
```yaml
name: environment-one
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - pip
  - gxx_linux-64=9.4.0
 ```

`environment-2.yaml`:
```yaml
name: environment-two
channels:
  - conda-forge
dependencies:
  - python=3.9.7
  - pip
  - gxx_linux-64=11.2.0
 ```

My current workaround involved creating two separate conda-vendor'ed local-channels for each `environment.yaml`, then manually combining the `.tar.bz2` packages into one local-channel, deleting the `repodata.json` files, re-indexing that channel with `conda index .`, and then manually merging the meta-manifest files into one (removing any duplicate entries). 

It would be awesome to have the ability to create a single local channel from multiple `environment.yaml` files without the workaround!
